changed api adress to sandbox
NOGStudio/qonto-php pull request #1
Opened 2023-02-07 13:16 UTC by Dekleor

2023-02-07 15:04 UTC, Dekleor commented
Address seems to be wrong, trying to fix it :)

2023-02-08 12:52 UTC, MrVinceZ requested changes
Hum.. la const QONTO_URL n'est necessaire que dans le send_request ?

Je pense que ce serait plus viable d'avoir deux const QONTO_URL et SANDBOX_URL et de choisir via un parametre optionnel (à false par defaut = use_sandbox)

2023-02-08 12:55 UTC, MrVinceZ commented
```
    private function sendRequest($url, array $parameters = [], $sandbox=false){
        if(! $this->login || ! $this->secret_key){
            trigger_error("Qonto credentials not filled !");
            return null;
        }

        if(! $this->login || ! $this->secret_key){
            $url = self::SANDBOX_URL.$url;
        } else {
            $url = self::QONTO_URL.$url;
        }

        $response = self::$guzzle_client->request('GET', $url, [
            'query' => $parameters,
            'headers' => [
                'Authorization' => $this->login.':'.$this->secret_key
            ],
        ])->getBody();

        return \GuzzleHttp\json_decode($response, true);
    }
```

2023-02-10 13:38 UTC, MrVinceZ approved these changes

2023-02-10 13:38 UTC, merged